name: Build APK

# Triggers
on:
  push:
    branches:
      - M1          # Run automatically on M1 branch
  workflow_dispatch:  # Allows manual run

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest

    steps:
      #Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      #Set up Java JDK 17
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      #Add KeyStore file
      - name: Add KeyStore file
        run: |
          echo "${{secrets.KEYSTORE}}" | base64 --decode > debug.keystore
          mkdir -p ~/.config/.android
          mv debug.keystore ~/.config/.android/debug.keystore

      #Add google services file
      - name: Add google services json
        run: |
          echo "${{ secrets.GOOGLE_SERVICES }}" | base64 --decode > AgriHealth-Alert-main/app/google-services.json

      #add map api key
      - name: Add map api key
        run: echo "MAPS_API_KEY=${{secrets.MAPS_API_KEY}}" > AgriHealth-Alert-main/local.properties

      #Build the debug APK
      - name: Build APK
        run: |
          cd AgriHealth-Alert-main && ./gradlew assembleDebug

      #Upload the APK as artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: APK
          path: AgriHealth-Alert-main/app/build/outputs/apk/debug/app-debug.apk
          overwrite: true
