name: Build APK

# Triggers
on:
  push:
    branches:
      - M1          # Run automatically on M1 branch
  workflow_dispatch:  # Allows manual run

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest

    steps:
      #Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      #Set up Java JDK 17
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: SignReport
        run: cd AgriHealth-Alert-main && ./gradlew signingReport

      #Add google services file
      - name: Add google services json
        run: |
          echo "${{ secrets.GOOGLE_SERVICES }}" | base64 --decode > AgriHealth-Alert-main/app/google-services.json

      #Build the debug APK
      - name: Build APK
        run: cd AgriHealth-Alert-main && ./gradlew assembleDebug

      #Upload the APK as artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: M1-APK
          path: AgriHealth-Alert-main/app/build/outputs/apk/debug/app-debug.apk
          overwrite: true
